import { matchList } from 'src/services/matchList'

const contacts = [
  {
    'Owner Name': 'ABELINA TORAL',
    'Property Address': '417 HILDA ST',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ADAM R KRISS',
    'Property Address': '1422 SE 209TH AVE',
    City: 'GRESHAM',
    State: 'OR',
    'Zip code': 97030,
  },
  {
    'Owner Name': 'ADAM SLAUGHTER',
    'Property Address': '16857 S HOLCOMB BLVD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ADRIAN RADUTIU',
    'Property Address': '16049 SE PEACE CT',
    City: 'HAPPY VALLEY',
    State: 'OR',
    'Zip code': 97086,
  },
  {
    'Owner Name': 'ALEXANDR BACHINSKY',
    'Property Address': '14071 SE SUNSHADOW ST',
    City: 'HAPPY VALLEY',
    State: 'OR',
    'Zip code': 97086,
  },
  {
    'Owner Name': 'ALEKSANDR KOTELYANETS',
    'Property Address': '711 JUNE DR',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'ALEXA L PATTI',
    'Property Address': '16600 S PAM DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ALICIA MARIE CURTISS',
    'Property Address': '45583 SEAGULL WAY',
    City: 'TEMECULA',
    State: 'CA',
    'Zip code': 92592,
  },
  {
    'Owner Name': 'ALLISON R WEAVER',
    'Property Address': '18739 SUNBLAZE DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ALYSSA BECK',
    'Property Address': '527 NW ELM ST',
    City: 'CAMAS',
    State: 'WA',
    'Zip code': 98607,
  },
  {
    'Owner Name': 'ALYSSA L BRITTON',
    'Property Address': '19435 ORCHARD GROVE DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ALYSSA HANSEN',
    'Property Address': '12713 VILLARD PL',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'AMANDA WHITMAN',
    'Property Address': '16625 S REDLAND RD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'AMANDA M EDWARDS',
    'Property Address': '2136 N LOCUST ST',
    City: 'CANBY',
    State: 'OR',
    'Zip code': 97013,
  },
  {
    'Owner Name': 'AMANDA HOLLIS',
    'Property Address': '14018 S SPANGLER RD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'AMIE M KILGORE',
    'Property Address': '200 NW 95TH ST',
    City: 'REDMOND',
    State: 'OR',
    'Zip code': 97756,
  },
  {
    'Owner Name': 'AMY ROEGER',
    'Property Address': '16632 TUDOR DR',
    City: 'GLADSTONE',
    State: 'OR',
    'Zip code': 97027,
  },
  {
    'Owner Name': 'AMY COOK',
    'Property Address': '5845 SE HULL AVE',
    City: 'MILWAUKIE',
    State: 'OR',
    'Zip code': 97267,
  },
  {
    'Owner Name': 'AMY E SCHAFER',
    'Property Address': '13830 SE CENTER ST',
    City: 'PORTLAND',
    State: 'OR',
    'Zip code': 97236,
  },
  {
    'Owner Name': 'ANABELA A PARIS',
    'Property Address': '13390 EASTBORNE DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ANABELA A PARIS',
    'Property Address': '2670 W SEGERSTROM AVE D',
    City: 'SANTA ANA',
    State: 'CA',
    'Zip code': 92704,
  },
  {
    'Owner Name': 'ANDREA D GARCIA',
    'Property Address': '1045 COLUMBIA AVE',
    City: 'GLADSTONE',
    State: 'OR',
    'Zip code': 97027,
  },
  {
    'Owner Name': 'ANDREW J ROBERGE',
    'Property Address': '1641 SW MIRANDA PL',
    City: 'TROUTDALE',
    State: 'OR',
    'Zip code': 97060,
  },
  {
    'Owner Name': 'ANDREW D HUNGERFORD',
    'Property Address': '13238 S SPANGLER RD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ANGELA HESS',
    'Property Address': '18221 S SILVERWOOD DR 259',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ANGELA PETTIT',
    'Property Address': '15337 S MAPLELANE RD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ANJALI BATES',
    'Property Address': '14060 S CANYON RIDGE DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ANN E HOVDA',
    'Property Address': '13705 SE 117TH CT',
    City: 'CLACKAMAS',
    State: 'OR',
    'Zip code': 97015,
  },
  {
    'Owner Name': 'ANNE SADOWSKI',
    'Property Address': '30902 NE SPUD MOUNTAIN RD',
    City: 'CAMAS',
    State: 'WA',
    'Zip code': 98607,
  },
  {
    'Owner Name': 'APRIL D MOLES',
    'Property Address': '13171 GAFFNEY LN',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'AREND M KOLEN',
    'Property Address': '16642 S ANNETTE DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ARLIN HERNANDEZ',
    'Property Address': '4102 SYLVIA ST SE',
    City: 'SALEM',
    State: 'OR',
    'Zip code': 97317,
  },
  {
    'Owner Name': 'ARNOLD KELLER',
    'Property Address': '4401 SE HARRISON ST',
    City: 'MILWAUKIE',
    State: 'OR',
    'Zip code': 97222,
  },
  {
    'Owner Name': 'ASHLEY E OLIPHANT',
    'Property Address': '14635 COLTRANE ST',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ASHLEY E TODD',
    'Property Address': '966 N BIRCH ST',
    City: 'CANBY',
    State: 'OR',
    'Zip code': 97013,
  },
  {
    'Owner Name': 'ASHLEY M BEHRENDT',
    'Property Address': '13260 DEER MEADOWS RD',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'AUSTIN FIELDS',
    'Property Address': '215 SMITH ST',
    City: 'SILVERTON',
    State: 'OR',
    'Zip code': 97381,
  },
  {
    'Owner Name': 'APRIL SMITH',
    'Property Address': '532 DIVISION ST',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'R ALAN CURTEMAN',
    'Property Address': '21685 S MCBURNEY RD',
    City: 'BEAVERCREEK',
    State: 'OR',
    'Zip code': 97004,
  },
  {
    'Owner Name': 'BARBARA K LARSON',
    'Property Address': '1414 SE 208TH AVE',
    City: 'GRESHAM',
    State: 'OR',
    'Zip code': 97030,
  },
  {
    'Owner Name': 'BENJAMIN M SMITH',
    'Property Address': '20856 S SPRINGWATER RD',
    City: 'ESTACADA',
    State: 'OR',
    'Zip code': 97023,
  },
  {
    'Owner Name': 'BENJAMIN H SMALLEY',
    'Property Address': '730 ANDRIAN DR',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'BENJAMIN M BURKLUND',
    'Property Address': '1112 MEADOW DR',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'MARTA DRAGOMIR',
    'Property Address': '4517 SE HILL RD',
    City: 'MILWAUKIE',
    State: 'OR',
    'Zip code': 97267,
  },
  {
    'Owner Name': 'ALBINA ELIZABETH ANDERSON',
    'Property Address': '12838 S BARNARDS RD',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'ANDREW JAY KEEN',
    'Property Address': '174 KING ST',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'BETINA MORTENSEN',
    'Property Address': '5807 SE 99TH AVE',
    City: 'PORTLAND',
    State: 'OR',
    'Zip code': 97266,
  },
  {
    'Owner Name': 'BETSY Z BOTHWELL',
    'Property Address': '202 E 3RD ST',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'AMANDA ROBERGE',
    'Property Address': '1641 SW MIRANDA PL',
    City: 'TROUTDALE',
    State: 'OR',
    'Zip code': 97060,
  },
  {
    'Owner Name': 'TROY L LAYTON',
    'Property Address': '622 JUNE DR',
    City: 'MOLALLA',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'WILLIAM R DAVEY',
    'Property Address': '29701 S MARSHALL RD',
    City: 'MULINO',
    State: 'OR',
    'Zip code': 97042,
  },
  {
    'Owner Name': 'BLAZE C RIGGINS',
    'Property Address': '19714 CHERRYWOOD WAY',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ROBERT W MUELLER',
    'Property Address': '19427 WESTWOOD DR',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'ROBERT M GANGWER',
    'Property Address': '16888 SE MADUROS CT',
    City: 'DAMASCUS',
    State: 'OR',
    'Zip code': 97089,
  },
  {
    'Owner Name': 'BRANDEE L OSTER',
    'Property Address': '651 SE 137TH AVE',
    City: 'PORTLAND',
    State: 'OR',
    'Zip code': 97233,
  },
  {
    'Owner Name': 'BRANDON S HANSON',
    'Property Address': '16401 HUNTER AVE',
    City: 'OREGON CITY',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'BRANDON A LAMM',
    'Property Address': '700 NE FOOTHILLS DR',
    City: 'ESTACADA',
    State: 'OR',
    'Zip code': 97023,
  },
  {
    'Owner Name': 'BRANDON SMITH',
    'Property Address': '22610 S FOREST PARK RD',
    City: 'BEAVERCREEK',
    State: 'OR',
    'Zip code': 97004,
  },
  {
    'Owner Name': 'Adrienne Jess',
    'Property Address': '28240 SW Paris Ave',
    City: 'Wilsonville',
    State: 'OR',
    'Zip code': 97070,
  },
  {
    'Owner Name': 'Alan Curteman',
    'Property Address': '21685 South McBurney Road',
    City: 'Beavercreek',
    State: 'OR',
    'Zip code': 97004,
  },
  {
    'Owner Name': 'Alberto Hernandez',
    'Property Address': '685 Andrian Dr',
    City: 'Molalla',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'Alejandra Mendoza',
    'Property Address': '8510 Southeast Down Way',
    City: 'Milwaukie',
    State: 'OR',
    'Zip code': 97267,
  },
  {
    'Owner Name': 'Alex Andras',
    'Property Address': '15248 S Carus Rd',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Alex Grigorov',
    'Property Address': '15058 SE Armel Dr',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Alex Koval',
    'Property Address': '16337 Chapin Way',
    City: 'Lake Oswego',
    State: 'OR',
    'Zip code': 97034,
  },
  {
    'Owner Name': 'Alexis Myhrum',
    'Property Address': '15471 Penny Avenue',
    City: 'Sandy',
    State: 'OR',
    'Zip code': 97055,
  },
  {
    'Owner Name': 'Alise Varella',
    'Property Address': '7373 Southeast Clackamas Road',
    City: 'Milwaukie',
    State: 'OR',
    'Zip code': 97267,
  },
  {
    'Owner Name': 'Alyssa Christensen',
    'Property Address': '9354 Saint Paul Highway Northeast',
    City: 'Aurora',
    State: 'OR',
    'Zip code': 97002,
  },
  {
    'Owner Name': 'Amanda Cox',
    'Property Address': '1606 Northeast 156th Street',
    City: 'Vancouver',
    State: 'WA',
    'Zip code': 98686,
  },
  {
    'Owner Name': 'Amanda White',
    'Property Address': '8640 Southeast Causey Avenue Apt Q103',
    City: 'Happy Valley',
    State: 'OR',
    'Zip code': 97086,
  },
  {
    'Owner Name': 'Amber & Timothy Gunter',
    'Property Address': '15450 South Tioga Road',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Amber McLean',
    'Property Address': '6525 SE Jordan St',
    City: 'Milwaukie',
    State: 'OR',
    'Zip code': 97222,
  },
  {
    'Owner Name': 'Amie Krueger',
    'Property Address': '9641 SE Harold St',
    City: 'Portland',
    State: 'OR',
    'Zip code': 97266,
  },
  {
    'Owner Name': 'Amy Reusser',
    'Property Address': '21611 Oregon 213',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'and Brenda & Ed Milano Jr',
    'Property Address': '27419 V Street',
    City: 'Ocean Park',
    State: 'WA',
    'Zip code': 98640,
  },
  {
    'Owner Name': 'Andrew Worthington',
    'Property Address': '17818 South Harding Road',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Andrew Turner',
    'Property Address': '1475 Northeast Kristie Lane',
    City: 'Estacada',
    State: 'OR',
    'Zip code': 97023,
  },
  {
    'Owner Name': 'Andy Laken',
    'Property Address': '3632 NE 66th Ave',
    City: 'Portland',
    State: 'OR',
    'Zip code': 97213,
  },
  {
    'Owner Name': 'Angela Atkins',
    'Property Address': '13418 Squire Drive',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': "Angela O'Dell",
    'Property Address': '640 Lakota Lane',
    City: 'Molalla',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'Angela Pederson',
    'Property Address': '17678 South Gronlund Road',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Angie Gonzalez',
    'Property Address': 'PO Box 3065',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Ann McFall',
    'Property Address': '22514 Southeast Stark Street #120',
    City: 'Gresham',
    State: 'OR',
    'Zip code': 97030,
  },
  {
    'Owner Name': 'Anna Demouchet',
    'Property Address': '2555 SW Elmhurst Ave',
    City: 'Beaverton',
    State: 'OR',
    'Zip code': 97005,
  },
  {
    'Owner Name': 'Anna Shelton',
    'Property Address': '18703 Sunblaze Drive',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Anna Lerum',
    'Property Address': '12651 Trade Wind Street',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'April Smith',
    'Property Address': '532 Division St',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Arlin Hernandez',
    'Property Address': '4102 Sylvia Street Southeast',
    City: 'Salem',
    State: 'OR',
    'Zip code': 97317,
  },
  {
    'Owner Name': 'Ashley Wolfe',
    'Property Address': '1102 Simmons Street',
    City: 'Gladstone',
    State: 'OR',
    'Zip code': 97027,
  },
  {
    'Owner Name': 'Audra Fullen',
    'Property Address': '13920 Conway Drive',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Barbara Dietz',
    'Property Address': '2438 SE 190th Ave',
    City: 'Portland',
    State: 'OR',
    'Zip code': 97233,
  },
  {
    'Owner Name': 'Barbara Dalling',
    'Property Address': '43641 Riverpoint Dr',
    City: 'Leesburg',
    State: 'VA',
    'Zip code': 20176,
  },
  {
    'Owner Name': 'Benjamin Parsons',
    'Property Address': '11098 Southwest Marilyn Street',
    City: 'Tualatin',
    State: 'OR',
    'Zip code': 97062,
  },
  {
    'Owner Name': 'Benny Damian',
    'Property Address': '5987 SE Robhil Dr',
    City: 'Milwaukie',
    State: 'OR',
    'Zip code': 97222,
  },
  {
    'Owner Name': 'Betsy Gunderson',
    'Property Address': '419 Irving Street',
    City: 'Oregon City',
    State: 'OR',
    'Zip code': 97045,
  },
  {
    'Owner Name': 'Bev Woster',
    'Property Address': '12906 S Bobby Bruce Lane',
    City: 'Boring',
    State: 'OR',
    'Zip code': 97009,
  },
  {
    'Owner Name': 'Blanca Skaggs',
    'Property Address': '33760 S Dickey Prairie Rd',
    City: 'Molalla',
    State: 'OR',
    'Zip code': 97038,
  },
  {
    'Owner Name': 'Bob and Mary Jane Hevlin',
    'Property Address': '718 E Lincoln St',
    City: 'Carlton',
    State: 'OR',
    'Zip code': 97111,
  },
  {
    'Owner Name': 'Bob Hanley',
    'Property Address': '20943 SE Main Drive',
    City: 'Gresham',
    State: 'OR',
    'Zip code': 97030,
  },
  {
    'Owner Name': 'Bonnie Jeruis',
    'Property Address': '5661 1st Court',
    City: 'West Linn',
    State: 'OR',
    'Zip code': 97068,
  },
]

export const handler = async () => {
  // Only allow POST requests
  // if (event.httpMethod !== 'POST') {
  //   return {
  //     status: 405,
  //     body: JSON.stringify({ error: 'Method Not Allowed' }),
  //   }
  // }

  try {
    const data = await matchList(777205, contacts)
    return {
      statusCode: 200,
      body: JSON.stringify(data),
    }
  } catch (error) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: 'Bad Request: ' + error.message }),
    }
  }
}
